var product_list = [
  {
    'name': 'Blazer',
    'picture': 'images/products/blazer1.jpeg',
    'old_price': 8000,
    'price': 5000,
    'discount': '',
    'stock': '',
  },
  {
    'name': 'Red Dress',
    'picture': 'images/products/dress1.jpeg',
    'old_price': 5000,
    'price': 3000,
    'discount': '',
    'stock': '',
  },
  {
    'name': 'Heels',
    'picture': 'images/products/hills1.jpeg',
    'old_price': 3000,
    'price': 2500,
    'discount': '',
    'stock': '',
  },
  {
    'name': 'Pants',
    'picture': 'images/products/pants1.jpg',
    'old_price': 1000,
    'price': 800,
    'discount': '',
    'stock': '',
  },
  {
    'name': 'Pants',
    'picture': 'images/products/pants1.jpg',
    'old_price': 1000,
    'price': 800,
    'discount': '',
    'stock': '',
  },
  {
    'name': 'Skirt',
    'picture': 'images/products/skt2.jpeg',
    'old_price': 1000,
    'price': 700,
    'discount': '',
    'stock': '',
  },
  {
    'name': 'Shoes',
    'picture': 'images/products/shoe1.jpg',
    'old_price': 4000,
    'price': 1300,
    'discount': '',
    'stock': '',
  },
];